// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znmrgcmevjgifidyefrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpubXJnY21ldmpnaWZpZHllZnJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNDkwNzMsImV4cCI6MjA2MzgyNTA3M30.LtKTmWrYlyP-YXVUzY_N0LMxQAVasVIeulUsqXyZV9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);